changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bug Fixes
      labels:
        - bug fix
    - title: New Features
      labels:
        - enhancement
    - title: Misc
      labels:
        - "*"
