[package]
name = "gh-form"
version = "0.1.0"
authors = ["Yudai Nakata <yudai.nkt@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.5", features = ["derive"] }
maud = { version = "0.23.0", features = ["axum"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
