name: Tag a new version

on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: version-detection
        with:
          create-tag: false
          version-command: cargo read-manifest | jq -r .version
      - uses: mathieudutour/github-tag-action@v6
        with:
          custom_tag: ${{ steps.version-detection.outputs.current-version }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: ${{ steps.version-detection.outputs.previous-version != steps.version-detection.outputs.current-version }}
